### ISSUE TITLE
Dashboards are always created

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-Something#20]
CREATE_DASHBOARD and CLEAN_DASHBOARD have defaults set as `'False'`, which since that's a string, will cause `if CREATE_DASHBOARD` etc to always evaluate to True (since strings always evaluate to True). We should either change both defaults from `'False'` to `False` OR do string value checking like `if CREATE_DASHBOARD.lower()=='true'`. Do you have a preference?

**Comment by ErinWeisbart** [comment]
Happy to fix to either way. Do you have a preference?

**Comment by bethac07** [comment]
Dealer's choice
