### ISSUE TITLE
More intro level for documentation

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-Something#5]
Current documentation assumes you 
- Know what Docker is
- Know why Dockerizing a workflow is valuable (ease of use, reproducibility, etc)
- What is the actual problem we're solving here (we sort of have it in the "why do I want to use this", but it would be nice to have a higher level thing, and to have it probably literally first)

**Comment by ErinWeisbart** [comment]
I redid the intro to address these comments in [b755d83](https://github.com/DistributedScience/Distributed-Something/commit/b755d83b8763f1b2cda6ec25d4906e4eac231ef8)
